---
version: "2"
services:
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - ~/.docker/sabnzbd/config:/config
      - ~/.docker/sabnzbd/downloads/complete:/downloads
      - ~/.docker/sabnzbd/downloads/incomplete:/incomplete-downloads #optional
    ports:
      - 8080:8080
      - 9090:9090
    restart: unless-stopped
    
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
      - UMASK_SET=022 #optional
    volumes:
      - ~/.docker/sonarr/config:/config
      - /mnt/media/TV:/tv
      - ~/.docker/sabnzbd/downloads/complete:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
      - UMASK_SET=022 #optional
    volumes:
      - ~/.docker/radarr/config:/config
      - /mnt/media/Movies:/movies
      - ~/.docker/sabnzbd/downloads/complete:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
 
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
      - UMASK_SET=022 #optional
    volumes:
      - ~/.docker/lidarr/config:/config
      - /mnt/media/Music:/music
      - ~/.docker/sabnzbd/downloads/complete:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
