---
version: "2"
services:
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ~/config/sabnzbd:/config
      - /mnt/media/downloads/complete:/downloads
      - /mnt/media/downloads/incomplete:/incomplete-downloads #optional
    ports:
      - 8080:8080
      - 9090:9090
    restart: unless-stopped
    
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK_SET=022 #optional
    volumes:
      - ~/config/sonarr:/config
      - /mnt/media/TV:/tv
      - /mnt/media/downloads/complete:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK_SET=022 #optional
    volumes:
      - ~/config/radarr:/config
      - /mnt/media/Movies:/movies
      - /mnt/media/downloads/complete:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
 
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK_SET=022 #optional
    volumes:
      - ~/config/lidarr:/config
      - /mnt/media/Music:/music
      - /mnt/media/downloads/complete:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped

  organizr:
    image: linuxserver/organizr
    container_name: organizr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ~/config/organizr:/config
    ports:
      - 9983:80
    restart: unless-stopped
